"""add quantity column to receipt items

Revision ID: 8f0dc8c066ce
Revises: 71a8c8ede669
Create Date: 2026-08-03 11:34:54.049898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f0dc8c066ce'
down_revision: Union[str, Sequence[str], None] = '71a8c8ede669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt_items', sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt_items', 'quantity')
    # ### end Alembic commands ###
